-- Governed access patterns for agentic and analytical workloads.

-- Roles
CREATE ROLE IF NOT EXISTS MEMBER_NAV_AGENT_ROLE;
CREATE ROLE IF NOT EXISTS MEMBER_NAV_ANALYST_ROLE;

-- Agent service account: read gold KB + search only
GRANT USAGE ON DATABASE AI TO ROLE MEMBER_NAV_AGENT_ROLE;
GRANT USAGE ON SCHEMA AI.GOLD TO ROLE MEMBER_NAV_AGENT_ROLE;
GRANT USAGE ON SCHEMA AI.MEMBER_NAV TO ROLE MEMBER_NAV_AGENT_ROLE;
GRANT SELECT ON TABLE AI.GOLD.MEMBER_KB TO ROLE MEMBER_NAV_AGENT_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE MEMBER_NAV_AGENT_ROLE;

-- Analysts: semantic views + structured gold, no raw bronze PII
GRANT USAGE ON SCHEMA AI.SEMANTIC TO ROLE MEMBER_NAV_ANALYST_ROLE;
GRANT USAGE ON SCHEMA AI.GOLD TO ROLE MEMBER_NAV_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA AI.SEMANTIC TO ROLE MEMBER_NAV_ANALYST_ROLE;
GRANT SELECT ON TABLE AI.GOLD.PLAN_COST_SHARING TO ROLE MEMBER_NAV_ANALYST_ROLE;

-- Dynamic masking on hashed member identifiers in bronze (illustrative)
CREATE OR REPLACE MASKING POLICY AI.BRONZE.MASK_MEMBER_HASH AS (val STRING)
  RETURNS STRING ->
    CASE
      WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'MEMBER_NAV_ANALYST_ROLE') THEN val
      ELSE '***'
    END;

-- Row access policy: agents see only active KB documents (defense in depth)
CREATE OR REPLACE ROW ACCESS POLICY AI.GOLD.RAP_ACTIVE_KB_ONLY
  AS (is_active BOOLEAN) RETURNS BOOLEAN ->
    is_active = TRUE OR CURRENT_ROLE() = 'ACCOUNTADMIN';

ALTER TABLE AI.GOLD.MEMBER_KB
  ADD ROW ACCESS POLICY AI.GOLD.RAP_ACTIVE_KB_ONLY ON (is_active);

COMMENT ON POLICY AI.GOLD.RAP_ACTIVE_KB_ONLY IS
    'Restrict agent and analyst reads to active knowledge documents.';
